const data = [
    {
        name: "Usep",
        jurusan: "Animasi",
        service: "Konseling Individual",
        category: "Pribadi",
        date: "12 April 2024",
        time: "14.00",
        location: "Lab PPLG",
        mentor: "Bu Devyta",
        detail: "Detail tentang Konseling Individual",
        status: "rejected"
    },
    {
        name: "Ani",
        jurusan: "Desain",
        service: "Konseling Kelompok",
        category: "Akademis",
        date: "15 April 2024",
        time: "10.00",
        location: "Ruang 101",
        mentor: "Pak Budi",
        detail: "Detail tentang Konseling Kelompok",
        status: "pending"
    },
    {
        name: "Budi",
        jurusan: "Teknik",
        service: "Konseling Online",
        category: "Karir",
        date: "20 April 2024",
        time: "16.00",
        location: "Zoom",
        mentor: "Ibu Siti",
        detail: "Detail tentang Konseling Online",
        status: "ongoing"
    },
        {
            "name": "Ronald",
            "jurusan": "Investment analyst",
            "service": "Konseling Online",
            "category": "Akademis",
            "date": "18 April 2024",
            "time": "16:00",
            "location": "Ruang 101",
            "mentor": "Pak Budi",
            "detail": "Sense step president range.",
            "status": "rejected"
        },
        {
            "name": "Jennifer",
            "jurusan": "Administrator, Civil Service",
            "service": "Konseling Individual",
            "category": "Akademis",
            "date": "05 April 2024",
            "time": "8:00",
            "location": "Ruang 101",
            "mentor": "Ibu Siti",
            "detail": "Heavy every cut near want.",
            "status": "rejected"
        },
        {
            "name": "Victor",
            "jurusan": "Higher education lecturer",
            "service": "Konseling Individual",
            "category": "Akademis",
            "date": "13 April 2024",
            "time": "16:00",
            "location": "Zoom",
            "mentor": "Bu Devyta",
            "detail": "Summer purpose relationship about both contain.",
            "status": "pending"
        },
        {
            "name": "Elizabeth",
            "jurusan": "Learning mentor",
            "service": "Konseling Kelompok",
            "category": "Pribadi",
            "date": "11 April 2024",
            "time": "12:00",
            "location": "Ruang 101",
            "mentor": "Ibu Siti",
            "detail": "Left deal month old. Whose protect gas.",
            "status": "done"
        },
        {
            "name": "Matthew",
            "jurusan": "Midwife",
            "service": "Konseling Individual",
            "category": "Akademis",
            "date": "01 April 2024",
            "time": "12:00",
            "location": "Lab PPLG",
            "mentor": "Ibu Siti",
            "detail": "Thank oil choose system.",
            "status": "pending"
        },
        {
            "name": "Grant",
            "jurusan": "Paramedic",
            "service": "Konseling Individual",
            "category": "Pribadi",
            "date": "15 April 2024",
            "time": "8:00",
            "location": "Zoom",
            "mentor": "Pak Budi",
            "detail": "Story billion thought friend.",
            "status": "pending"
        },
        {
            "name": "Ryan",
            "jurusan": "Herbalist",
            "service": "Konseling Individual",
            "category": "Pribadi",
            "date": "08 April 2024",
            "time": "17:00",
            "location": "Ruang 101",
            "mentor": "Bu Devyta",
            "detail": "Win young relationship drop force answer.",
            "status": "done"
        },
        {
            "name": "Nathan",
            "jurusan": "Chief Operating Officer",
            "service": "Konseling Kelompok",
            "category": "Karir",
            "date": "21 April 2024",
            "time": "10:00",
            "location": "Zoom",
            "mentor": "Ibu Siti",
            "detail": "Decide nature deep else friend.",
            "status": "rejected"
        },
        {
            "name": "Madison",
            "jurusan": "Pharmacologist",
            "service": "Konseling Online",
            "category": "Akademis",
            "date": "09 April 2024",
            "time": "12:00",
            "location": "Lab PPLG",
            "mentor": "Ibu Siti",
            "detail": "Cover play rock wind land factor later.",
            "status": "done"
        },
        {
            "name": "Kathryn",
            "jurusan": "Designer, graphic",
            "service": "Konseling Individual",
            "category": "Karir",
            "date": "15 April 2024",
            "time": "16:00",
            "location": "Ruang 101",
            "mentor": "Bu Devyta",
            "detail": "Behind son long approach blue.",
            "status": "reschedule"
        },
        {
            "name": "Kyle",
            "jurusan": "Horticultural consultant",
            "service": "Konseling Online",
            "category": "Karir",
            "date": "01 April 2024",
            "time": "9:00",
            "location": "Zoom",
            "mentor": "Pak Budi",
            "detail": "Without strategy how what rich thought.",
            "status": "upcoming"
        },
        {
            "name": "Clayton",
            "jurusan": "Dietitian",
            "service": "Konseling Individual",
            "category": "Pribadi",
            "date": "22 April 2024",
            "time": "11:00",
            "location": "Zoom",
            "mentor": "Pak Budi",
            "detail": "Moment role medical several thank together big.",
            "status": "pending"
        }
];

export default data;